source ~/.config/nvim/theme/nord.vim
source ~/.config/nvim/theme/ayu.vim
source ~/.config/nvim/theme/everforest.vim
source ~/.config/nvim/theme/material.vim
source ~/.config/nvim/plugins.vim
source ~/.config/nvim/settings.vim
source ~/.config/nvim/keymap.vim
source ~/.config/nvim/nvim-tree.vim
source ~/.config/nvim/coc.vim
source ~/.config/nvim/signify.vim
source ~/.config/nvim/telescope.vim
source ~/.config/nvim/octo.vim
